---

- name: Create app database
  postgresql_db: login_user=controller login_password="{{ postgres_controller_password }}" name=app owner=app encoding='UTF-8' lc_collate='en_GB.UTF-8' lc_ctype='en_GB.UTF-8' template='template0'