---
# Optionally create default 'app' database assigned to the app user

- name: Create app database
  postgresql_db: login_user=controller login_password="{{ postgresql_server_controller_postgresql_user_password }}" name="{{ postgresql_server_app_db_name }}" owner="{{ postgresql_server_app_db_owner }}" encoding='UTF-8' lc_collate='en_GB.UTF-8' lc_ctype='en_GB.UTF-8' template='template0' state=present
