---
# Configure PostgreSQL account for app user

- name: create pqsl history file for app OS user
  file: path=/home/app/.psql_history owner=app group=app state=touch

- name: create postgresql user account for app
  postgresql_user: name=app password="{{ postgresql_server_app_user_password }}" state=present
  sudo_user: postgres
