---
# Configure PostgreSQL account for controller user

- name: create pqsl history file for controller user
  file: path=/home/controller/.psql_history owner=controller group=controller state=touch

- name: create postgresql user account for controller
  postgresql_user: name=controller password="{{ postgresql_server_controller_user_password }}" role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB,REPLICATION state=present
  sudo_user: postgres
