---
# Install & Configure PostgreSQL server

- name: install postgresql server
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
  - postgresql
  - postgresql-contrib
  - python-psycopg2 # required for ansible to interface with database

- name: create pqsl history file for postgres user
  file: path=/var/lib/postgresql/.psql_history owner=postgres group=postgres state=touch

- name: configure pg_hba.conf
  template: src=etc/postgresql/9.3/main/pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres mode=640
  notify:
    - Restart PostgreSQL
- name: force handlers to run now
  meta: flush_handlers

- include: controller-user.yml
  when: postgresql_server_controller_postgresql_user_enabled == true

- include: app-user.yml
  when: postgresql_server_app_postgresql_user_enabled == true

- include: app-db.yml
  when: postgresql_server_create_app_db == true
